export const skills = {
    theObvious: [
      "Python",
      "JavaScript",
      "TypeScript",
      "C",
      "C++",
      "SQL",
      "HTML",
      "CSS",
      "Git",
    ],
    librariesFrameworks: [
      "React 18",
      "Node.js",
      "Express.js",
      "Vue 3",
      "Tailwind",
      "MaterialUI",
      "Ant Design",
      "DaisyUI",
      "Redux",
      "Tailwind ",
      "OAuth ",
    ],
    toolsOfTheTrade: [
      "Google Cloud Platform",
      "AWS",
      "MongoDB",
      "Docker ",
      "Kubernetes ",
      "RabbitMQ",
      "JWT",
      "PostMan",
      "npm / yarn/ bun",
      "Github",
      "VS Code",
    ]
  };